### ISSUE TITLE
Budget rhythms

### ISSUE THREAD

**Issue by satyaye** [satyaye/Satya#31]
1. Attrition - 

- Confirmed Attritions - 

> - Capture it from Workday first Monday of every month, and share in #india-budget. 
> - Alternately, M2 can proactively post any confirmed attrition in the #india-budget channel as soon as they see a confirmed attrition.

-  Potential Attrition - 

> - Admin to follow up with M2s, first Monday of every month, to get details. 
> - Alternately, M2s can proactively update the tracker (google sheet) as and when they sense a potential attrition and update Admin through slack.

2. Morale Spent - 
- First Monday of every month, Admin to send reminder to M2s for spent and remaining Morale Budget through email

3. Budget review
- First Wednesday Admin meeting of every month to have Budget Review as the agenda with limited audience (Sanjay, Business Manager & Vijaya)
- Budget review would include morale spent and point no. 3 below (Upcoming POs and Invoices)
- Meeting minutes to be recorded and followed up by Vijaya/Business Manager

4. Vendor PO and invoices
- Tracker is created to have PO and invoice details - Invoice number column to be added to the tracker for better readability
- Keep the tracker updated with the new invoices (majority of them get raised by 10th of every month)
- Send a slack message to Sanjay in Admin Channel, every second Friday of the month for him to check the tracker and approve invoices.

**Comment by smalpani-gh** [comment]
I would add following:
1. Taking action items from meeting and following up.
2. Morale budget spent across M2s.
3. List of upcoming budget spend and morale budget

**Comment by satyaye** [comment]
Incorporated feedback points. There would be other areas of expenses too like office space, could be more, where Admin does not  have visibility. Should those be tracked separately or made part of this sheet?

**Comment by satyaye** [comment]
The proposal is agreed by Sanjay & Vijaya, hence this issue can be closed. Here on Vijaya would be the DRI for ensuring this process is followed.
